### ISSUE TITLE
ReadMe.md - No releases

### ISSUE THREAD

**Issue by WustlRob** [chop-dbhi/data-models-packer#11]
I was checking to see if there was a newer version of the DCC Packager.  However, in the Install section of the Read Me, the link in "Download the latest binary from the _releases page _for your architecture" takes you to the Releases page that says "There aren’t any releases here".  Should I be looking elsewhere?

**Comment by murphyke** [comment]
Thanks for pointing that out; we'd better put a release up.  I'll let you know when that happens.

**Comment by murphyke** [comment]
@WustlRob I just put up the current binaries.  https://github.com/chop-dbhi/data-models-packer/releases/tag/1.0.0-beta  Thanks again.
