### ISSUE TITLE
Data Models Packer - http service 503

### ISSUE THREAD

**Issue by WustlRob** [chop-dbhi/data-models-packer#15]
@aaron0browne we're getting a 503 when we try to package our files.  Any suggestions?

>data-models-packer.exe -out input.tar.gz input
2017/03/06 10:29:03 packer: error creating or verifying metadata file: service 
**http://data-models.origins.link responded with status code 503**

**Comment by gracecodes144** [comment]
The data models service has moved and I haven't circled back to change the default setting in this package. Sorry!

Try running the same command with `--service="https://data-models-service.research.chop.edu"`.

**Comment by WustlRob** [comment]
Thanks for the workaround! It created the metadata file as expected.  We still have the issue we had last time where it can't be decompressed.  We're zipping the results an submitting that.

>data-models-packer.exe -out Temp data.tar.gz
2017/03/06 15:09:21 packer: error creating unpacking writer: gzip: invalid header
